# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  pool:
    name: WindowsReactAgent
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  
  - script: |
      npm install
      npm run build
      npm install --save-dev jest @testing-library/react @testing-library/jest-dom --force
      npm install --save-dev jest-html-reporter
    displayName: 'Install Dependencies and Build'
    
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'build'
      artifactName: 'drop'
    displayName: 'Publish Artifact'

- job: Test
  dependsOn: Build
  pool:
    name: WindowsReactAgent
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
    
  - script: |
      npm install
      npm test
    displayName: 'Run Tests'

- job: Deploy
  dependsOn: Test
  pool:
    name: WindowsReactAgent
  condition: succeeded()
  steps:
  - download: current
    artifact: drop
  - script: |
      # Add deployment steps here (e.g., deploying to Azure App Service, etc.)
    displayName: 'Deploy Calculadora Application'

